export const ADD_COURSES = 'ADD_COURSES'
export const CLEAR_COURSES = 'CLEAR_COURSES'

export const ADD_EVENTS = 'ADD_EVENTS'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const ADD_EVENT_ZOOM_LINKS = 'ADD_EVENT_ZOOM_LINKS'
