export const ADD_COURSES = 'ADD_COURSES'
export const CLEAR_COURSES = 'CLEAR_COURSES'

export const ADD_EVENTS = 'ADD_EVENTS'
export const CLEAR_EVENTS = 'CLEAR_EVENTS'
export const ADD_EVENT_ZOOM_LINKS = 'ADD_EVENT_ZOOM_LINKS'

export const ADD_COURSE_TEAMS_LINKS = 'ADD_COURSE_TEAMS_LINKS'
export const SET_COURSE_NOTE = 'ADD_COURSE_NOTE'
export const SET_COURSE_PLATFORM = 'SET_COURSE_PLATFORM'
export const CLEAR_COURSE_PLATFORM = 'CLEAR_COURSE_PLATFORM'

export const UPDATE_USER = 'UPDATE_USER'
export const CLEAR_USER = 'CLEAR_USER'

export const SET_FETCH_STATUS_MAIL = 'SET_FETCH_STATUS_MAIL'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'
export const SET_SHOWN_STATUS_GOOGLE_SETTINGS_MESSAGE = 'SET_SHOWN_STATUS_GOOGLE_SETTINGS_MESSAGE'
